# Generated by Django 3.0.6 on 2021-02-15 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firewall', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_password',
            new_name='username',
        ),
    ]
